### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tonyg** [rabbitmq/rabbitmq-udp-exchange#2]
### Describe the bug

Hi! I'm glad to see this plugin finally brought under the RabbitMQ project umbrella.

However, it looks (in commit c0cea61) like you're not complying with the original licence, which is MPL v2, and not MPL v2 plus Apache v2. Furthermore, you've added a number of copyright claims (VMware, Jon Brisbin, etc.) in the Apache boilerplate text that do not apply to this code.

If you'd like this code to be available under a different licence to the one it was provided to you under, please contact me. Otherwise, please revert back to the original licensing and remove the incorrect copyright attributions. Thank you!

### Reproduction steps

N/A

### Expected behavior

N/A

**Comment by lukebakken** [comment]
Hi @tonyg

Thank you for bringing this to our attention. I have reverted this repository to commit https://github.com/rabbitmq/rabbitmq-udp-exchange/commit/99ee53ffe6f34130920ae3a741ecf6d43955681b, which brings it back in-sync with your upstream at https://github.com/tonyg/udp-exchange/commit/99ee53ffe6f34130920ae3a741ecf6d43955681b

At this time I don't have an explanation for the license change, but my best guess is that it was during a time where we were "standardizing" licenses for all plugins under the https://github.com/rabbitmq organization. Team RabbitMQ is very sorry that it happened!

**Comment by michaelklishin** [comment]
This was a side effect of a number of changes too all repos under this org in 2018. We didn't mean to re-license this plugin specifically. All other repos I can think of use the same set of templates, and I suspect it was me who had synchronized them all with a script, without considering this plugin.
